# Generated by Django 5.2.7 on 2025-10-27 14:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=120, verbose_name='Libellé')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('montant_budget', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant du budget')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'db_table': 'budgets',
                'ordering': ['-date_debut', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depense', models.DateField(verbose_name='Date de dépense')),
                ('objet', models.CharField(max_length=255, verbose_name='Objet')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='depenses.budget', verbose_name='Budget associé')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'db_table': 'depenses',
                'ordering': ['-date_depense', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['utilisateur'], name='idx_budget_user'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['date_debut', 'date_fin'], name='idx_periode'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin__gte', models.F('date_debut'))), name='budget_periode_valide'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('montant_budget__gte', 0)), name='budget_montant_positif'),
        ),
        migrations.AddIndex(
            model_name='depense',
            index=models.Index(fields=['utilisateur'], name='idx_depense_user'),
        ),
        migrations.AddIndex(
            model_name='depense',
            index=models.Index(fields=['date_depense'], name='idx_date'),
        ),
        migrations.AddIndex(
            model_name='depense',
            index=models.Index(fields=['budget'], name='idx_budget'),
        ),
        migrations.AddConstraint(
            model_name='depense',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gte', 0)), name='depense_montant_positif'),
        ),
    ]
