# Generated by Django 5.2.7 on 2025-10-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=191, unique=True),
        ),
    ]
